### ISSUE TITLE
pip install issue:numpy version incompatiblle

### ISSUE THREAD

**Issue by Lvmoy** [yongzhuo/Macadam#3]
Pip install Macadam, report :_ERROR: nlg-yongzhuo 0.0.4 has requirement numpy==1.16.2, but you'll have numpy 1.18.1 which is incompatible.
ERROR: macropodus 0.0.6 has requirement numpy==1.16.2, but you'll have numpy 1.18.1 which is incompatible._

When i install macropodus manully, report: _ERROR: macadam 0.0.1 has requirement numpy==1.18.1, but you'll have numpy 1.16.2 which is incompatible._

**Comment by yongzhuo** [comment]
numpy版本冲突问题，最新的0.1.1版本已修复，numpy版本不是必须的，应该不会有什么影响。
